name: Test thing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  dothething:
    name: "Do the thing"
    runs-on: macos-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Restore packages
        run: npm install
      - name: Get the output
        run: node index.mjs
